# https://scotch.io/tutorials/build-and-deploy-a-serverless-function-to-netlify
# https://youtu.be/_1qXQM3Mt4Q

[build]
  command = "npm run build"
  publish = "_site/"
  functions = "it-seems-like-this-can-be-anything"
