[build]
  functions = "dist/lambda/" # the directory where the functions are published to when developing locally
  publish = "_site/" # the directory to publish the generated Jekyll site into
  command = "npm run build" # the build command to run when deployed
