[build]
  command = "npm run build" # the build command to run when deployed
  publish = "_site/" # the directory to publish the generated Jekyll site into
  functions = "it-seems-like-this-can-be-anything" # the directory where the functions are published to when developing locally
